from app.agents.base_agent import BaseAgent
from app.models import ProjectRequest, ProjectResponse, ProjectRecommendation, Milestone

class ProjectAgent(BaseAgent):
    def generate_projects(self, req: ProjectRequest) -> ProjectResponse:
        system_instruction = (
            "You are the Project Recommendation Agent for the Smart Student Success app. "
            "Your task is to recommend high-quality, practical project ideas for students based on their target domain, "
            "difficulty level, preferred tech stack, and scope. "
            "Each recommendation must include a title, description, core features, tech stack list, "
            "implementation milestones, and a complete GitHub-ready README.md template in markdown format."
        )
        
        prompt = (
            f"Generate project recommendations for the '{req.domain}' domain.\n"
            f"Difficulty Level: {req.difficulty}\n"
            f"Preferred Tech Stack: {', '.join(req.tech_stack)}\n"
            f"Scope: {req.project_scope}\n\n"
            "Return the project recommendations strictly matching the response schema."
        )
        
        def fallback():
            # Devise a creative project name and details based on domain
            domain_lower = req.domain.lower()
            stack_str = ", ".join(req.tech_stack)
            
            if "ai" in domain_lower or "ml" in domain_lower or "data" in domain_lower:
                p_title = "Aegis AI - Intelligent Student Diagnostic Analyzer"
                p_desc = f"An agentic AI analysis system that evaluates students' study records, homework submissions, and quiz performance to provide actionable study advice."
                p_features = [
                    "Gemini API structured diagnostic analyzer engine",
                    "Database dashboard to track student scores over time",
                    "Custom chart generator showing learning speed metrics",
                    "Automated PDF report generator for academic advisors"
                ]
            elif "web" in domain_lower or "app" in domain_lower:
                p_title = "EduSphere - Collaborative Class Workspace"
                p_desc = f"A real-time workspace for class notes, study guides, and discussion forums utilizing {stack_str}."
                p_features = [
                    "Real-time rich text note sync across classmates",
                    "Subject channels with folder structures for slide sharing",
                    "AI chatbot helper integrated directly into sidebar workspace",
                    "Interactive flashcard generator from notes"
                ]
            else:
                p_title = "DevForge - Tech Portfolio Optimizer"
                p_desc = f"A developer utility tool designed to analyze GitHub profile metrics, highlight project categories, and suggest templates using {stack_str}."
                p_features = [
                    "GitHub API data extraction integration",
                    "Automatic skill categorization parsing",
                    "Sleek SVG portfolio badge builder",
                    "Export to HTML/Markdown templates"
                ]
                
            readme_md = (
                f"# {p_title}\n\n"
                f"## Overview\n"
                f"{p_desc}\n\n"
                f"This project was generated by the **Smart Student Success Agent** as a customized **{req.difficulty}** recommendation "
                f"utilizing **{stack_str}**.\n\n"
                f"## Features\n"
                + "\n".join([f"- **{feat}**" for feat in p_features]) + "\n\n"
                f"## Getting Started\n\n"
                f"### Prerequisites\n"
                f"Ensure you have the latest packages installed for: `{', '.join(req.tech_stack[:3])}`.\n\n"
                f"### Installation\n"
                f"1. Clone the repository:\n"
                f"   ```bash\n"
                f"   git clone https://github.com/your-username/{p_title.lower().replace(' ', '-')}.git\n"
                f"   ```\n"
                f"2. Install dependencies:\n"
                f"   ```bash\n"
                f"   npm install  # or pip install -r requirements.txt\n"
                f"   ```\n"
                f"3. Create a `.env` file and configure your API keys.\n"
                f"4. Run the development server:\n"
                f"   ```bash\n"
                f"   npm run dev  # or uvicorn main:app --reload\n"
                f"   ```\n\n"
                f"## License\n"
                f"MIT License - Free to use and modify for student portfolios!"
            )
            
            milestones = [
                Milestone(
                    title="Phase 1: Setup & UI Scaffolding",
                    target_date="Milestone 1",
                    description=f"Initialize repo, configure Tailwind/styling, and build core dashboard views."
                ),
                Milestone(
                    title="Phase 2: Core Logic & API integration",
                    target_date="Milestone 2",
                    description=f"Implement backend services, integrate Gemini API or database interfaces, and verify responses."
                ),
                Milestone(
                    title="Phase 3: Deploy & Polish",
                    target_date="Milestone 3",
                    description="Write tests, optimize responsive layout, and deploy to Vercel/Render."
                )
            ]
            
            project_rec = ProjectRecommendation(
                title=p_title,
                difficulty=req.difficulty,
                description=p_desc,
                key_features=p_features,
                suggested_tech_stack=req.tech_stack,
                implementation_milestones=milestones,
                readme_template=readme_md
            )
            
            # Add a secondary simpler project just to give the student choices
            sec_title = f"Simple {req.domain} Portfolio Starter"
            sec_desc = f"A beginner-friendly project focused on modular coding best practices using {stack_str}."
            sec_features = [
                "Clean folder architecture templates",
                "Lightweight static views and widgets",
                "Local Storage integration for tracking settings"
            ]
            
            sec_readme = (
                f"# {sec_title}\n\n"
                f"A lightweight boilerplate project for {req.domain} students using `{stack_str}`.\n"
            )
            
            sec_milestones = [
                Milestone(
                    title="Setup & Localstorage",
                    target_date="Day 1-3",
                    description="Create static layouts and hook up input listeners."
                )
            ]
            
            sec_project = ProjectRecommendation(
                title=sec_title,
                difficulty="Beginner",
                description=sec_desc,
                key_features=sec_features,
                suggested_tech_stack=req.tech_stack[:2],
                implementation_milestones=sec_milestones,
                readme_template=sec_readme
            )
            
            return ProjectResponse(
                projects=[project_rec, sec_project]
            )
            
        return self.generate_structured_output(
            prompt=prompt,
            system_instruction=system_instruction,
            response_schema=ProjectResponse,
            fallback_func=fallback
        )
